version: '3.9' 

services:
  ollama:
    image: ollama/ollama:latest 
    container_name: security_ollama
    volumes:
      - ollama_data:/root/.ollama # ollama_data est le dossier dans lequel le modèle est stocké
    ports:
      - "11434:11434" # Syntaxe : port_du_PC : port_du_conteneur
    # Optionnel : décommenter si une carte graphique NVIDIA est disponible sur la machine hôte
    # deploy: [cite: 668]
    #   resources: [cite: 669]
    #     reservations: [cite: 670]
    #       devices: [{driver: nvidia, capabilities: [gpu]}] [cite: 671]

  chromadb: # mémoire documentaire RAG
    image: chromadb/chroma:latest
    container_name: security_chromadb
    volumes:
      - chroma_data:/chroma/.chroma 
    ports:
      - "8001:8000" # exposée sur le port 8001

  speaches: # Reconnaissance et synthèse vocale
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    container_name: security_speaches
    ports:
      - "8080:8080"

  app:
    build:
      context: . # Indique que la racine du projet est le dossier courant
      dockerfile: docker/app.Dockerfile 
    container_name: security_app
    ports:
      - "8000:8000" 
    depends_on:
      - ollama 
      - chromadb 
    environment:
      - OLLAMA_URL=http://ollama:11434 
      - CHROMA_HOST=chromadb 
      - CHROMA_PORT=8000 

volumes:
  ollama_data:
  chroma_data: